name: test-bot
on:
  push:
    branches: master
  pull_request:
jobs:
  test-bot:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: test-bot
        run: |
          set -e
          brew update
          for f in Formula/*.rb; do
            brew test-bot "$f"
          done
